# Tokyo Night color scheme for kitty
# https://github.com/folke/tokyonight.nvim

foreground #a9b1d6
background #1a1b26
selection_foreground #c0caf5
selection_background #364a82

url_color #73daca

# Black
color0 #414868
color8 #565f89

# Red
color1 #f7768e
color9 #f7768e

# Green
color2  #9ece6a
color10 #9ece6a

# Yellow
color3  #e0af68
color11 #e0af68

# Blue
color4  #7aa2f7
color12 #7aa2f7

# Magenta
color5  #bb9af7
color13 #bb9af7

# Cyan
color6  #7dcfff
color14 #7dcfff

# White
color7  #a9b1d6
color15 #c0caf5

# Cursor
cursor #c0caf5
cursor_text_color #1a1b26

# Tab bar
active_tab_foreground   #c0caf5
active_tab_background   #1a1b26
inactive_tab_foreground #565f89
inactive_tab_background #1a1b26
tab_bar_background #24283b
